"""add group session model

Revision ID: 0764265b007f
Revises: 0a4f1f2c2f5a
Create Date: 2025-12-06 19:26:40.690929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0764265b007f'
down_revision: Union[str, Sequence[str], None] = '0a4f1f2c2f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('group_sessions',
    # sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    # sa.Column('group_id', sa.UUID(), nullable=False),
    # sa.Column('video_id', sa.UUID(), nullable=False),
    # sa.Column('video_name', sa.String(length=255), nullable=True),
    # sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    # sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('group_sessions')
    # ### end Alembic commands ###
