"""add engagement

Revision ID: 545875f9925b
Revises: 15b2777f46ea
Create Date: 2025-12-06 11:47:43.221978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545875f9925b'
down_revision: Union[str, Sequence[str], None] = '15b2777f46ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('relaxation', sa.Float(), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=False),
    sa.Column('screenshot_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engagements')
    # ### end Alembic commands ###
