"""add user role

Revision ID: a8834174e6b6
Revises: f13d0d866596
Create Date: 2025-12-06 10:06:15.362658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8834174e6b6'
down_revision: Union[str, Sequence[str], None] = 'f13d0d866596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pair_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("TIMEZONE('utc', now()) + INTERVAL '60 minutes'"),
               existing_nullable=False)
    op.add_column('users', sa.Column('role', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.alter_column('pair_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(timezone('utc'::text, now()) + '00:05:00'::interval)"),
               existing_nullable=False)
    # ### end Alembic commands ###
