"""enhance engagements

Revision ID: adf3f0388781
Revises: 0764265b007f
Create Date: 2025-12-06 20:22:39.898642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf3f0388781'
down_revision: Union[str, Sequence[str], None] = '0764265b007f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_group_member', 'group_members', type_='unique')
    # ### end Alembic commands ###
